-
  name: Simple loop example
  hosts: all
  tasks:
    - name: Iterate over the loop
      debug:
          msg: "My name is : {{ item }}"
      loop:
          - Akash
          - DevOps
          - Ansible
